### ISSUE TITLE
API path is wrong for Ilceler

### ISSUE THREAD

**Issue by marifdev** [furkantektas/EzanVaktiAPI#1]
In the new website, API path for Ilce information is added as:
İlçeler Listesi: GET `[/ilce/[SEHIR_KODU]]`

It should be `/ilceler/[SEHIR_KODU]`

**Comment by furkantektas** [comment]
Thanks a lot, fixed. 

Çok teşekkür ederim Arif bey :)

**Comment by marifdev** [comment]
rica ederim :)
Bu API'i sagladiginiz icin ben tesekkur ederim
